[project]
name = "embedded-prac"
version = "0.1.0"
description = "Repository to host some embedded related knowledge"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]
